### ISSUE TITLE
ERROR: No matching distribution found for wpconfigr

### ISSUE THREAD

**Issue by captainreptile** [cariad/wp-configr#6]
Hello,
I would love to use this package with python3, however i can't find it on pypi.org and pip3 install wpconfigr returns:

> ERROR: Could not find a version that satisfies the requirement wpconfigr (from versions: none)
> ERROR: No matching distribution found for wpconfigr

Any suggestions or is it depreciated?

**Comment by cariad** [comment]
Well, that was weird!

It looks like I deleted the package (probably a few years ago when it looked like it wasn't getting any use). I tried to republish, but it failed because PyPI reserves names of deleted packages.

So, I've renamed and republished the package as-is as `wpconfigger`. It _should_ just work, but this code is old and embarrassing so let me know if it's still broken? :sweat_smile: 

Thanks!

**Comment by captainreptile** [comment]
Thanks for the quick reply :)

I spent some good time trying to use only the relevant code snippet (fetch DB Auth data), but it didn't work so i tried to install all the library.
In the meantime i figured that code snippet didn't work because wp-config.php had **‘ ’** instead of  **' '** and now i fixed it.

Thanks for the module, i find it very useful for various operations related wordpress :)
